Dict = {
    "powering": "how are you",
    "hollering": "hello",
    "hu r u": "who are you",
    "how r u": "how are you",
    "sif can": "shift command",
    "saved": "save",
    "mike off": "mic off",
    "notepade": "notepad",
    "ise": "is",
    "press centre": "press entre",
    "pre senter": "press enter",
    "precept": "press shift",
    "receipt": "press shift",
    "stop": "stop",
    "control sev" :"control save",
   "conrol save" : "control save",
    "precious": "press shift",
    "pressure dar": "press alter",
    "press filter": "press alter",
    " pressure dar": "press alter",
    "crescent": "press alter",
    "press halter": "press alter",
    "press catalogue": "press cap",
    "press capital": "press cap",
    "prescribe": "press cap",
    "prescription": "press cap",
    "press capital": "press cap",
    "press step button": "press tab button",
    "step button": "press tab button",
    "prestige": "press cap",
    "press insert": "press insert",
    "press inside": "press insert",
    "press page": "press page up",
    "press bhejo": "press page up",
    "press tape button": "press tab button",
    "press tap button": "press tab button",
    "press the express": "press  back space",
    "press express": "press back space",
    "press back": "press backspace",
    "press press": "press space",
    "press space": "press space",
    "press shift": "press hash sign",
    "press s sign": "press hash sign",
    "press hairstyle": "press hash sign",
    "pressure sign": "press hash sign",
    "tress modular": "press modular",
    "race modular": "press modular",
    "press dollar sign": "press dollar",
    "crash class": "press plus",
    "press note": "press dote",
    "press di": "press dote",
    "door": "press dote",
    "road": "press dote",
    "press de": "press dote",
    "press prestige": "press dote",
    "fresh di": "press dote",
    "race 1": "press  1",
    "presto": "press  2",
    "race 2": "press  2",
    "race 3": "press  3",
    "krish 4": "press  4",
    "press zero": "press  0",
    "press hero": "press 0",
    "press ps4": "press 4",
    "race 4": "press 4",
    "press phone": "press 4",
    "prefix": "press 6",
    "precis": "press 6",
    "press file": "press 5",
    "race 7": "press 7",
    "present": "press 8",
    "press on": "press 8",
    "press hot": "press 8",
    "press art": "press 8",
    "pareshan": "press 8",
    "fresh art": "press 8",
    "yes capital": "press S",
    "test capital": "press S",
    "as capital": "press S",
    "face capital": "press S",
    "krishna": "press 9",
    "race 5": "press 5",
    "krrish 5": "press 5",
    "race 9": "press 9",
    "prashn": "press 9",
    "harsh 9": "press 9",
    "recite": "press 8",
    "parasite": "press 8",
    "press coma": "press comma",
     "class": "class",
    "glass": "class",  # common mishear
    "imt": "int",
    "ind": "int",
    "aunty": "int",
    "and": "int",      # sometimes misheard
    "float": "float",
    "flute": "float",
    "load": "float",
    "string": "String",
    "boolean": "boolean",
    "float mi": "float b",
    "84":"javac",
    "give me class": "class",
    "press karle open": "{",
     "dot":".",
     "dotout":".out",
    "door": ".",
    "devote": ".",
    "tot": ".",
    "iot": ".",
    "press question mark": "?",
    

     "p r i n t":"print",
    "press kar le open": "{",
    "press kar le close": "}",
    "press kar li close": "}",
    "press curly close": "}",
    "press square open": "[",
    "press square close": "]",
    "press round open": "(",
    "press round close": ")",
    "press hash": "#",
    "press dollar": "$",
    "press percent": "%",
    "press and": "&",
    "press star": "*",
    "press plus": "+",
    "press minus": "-",
    "press slash": "/",
    "press equal": "=",
    "press space": " ",
    "press comma": ",",
    "press semicolon": ";",
    "press double coat": "\"",
    "press single coat": "\'",
    "press less than": "<",
    "press greater than": ">",
    "press semicolon": ";",
    "press semicon": ";",
    "semicolon": ";",



}

def fix_phrase(text):
    # Agar text exact mapping me milta hai to replace karo
    if text.lower() in Dict:
        return Dict[text.lower()]
    return text